apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dcw-my
namePrefix: jsplumb
nameSuffix: prod

commonLabels:
  app: jsplumb-prod

resources:
  - deploy.yaml
  - svc.yaml

images:
  - name: baseimage
    newName: hub.dev.laningtech.net/apps/dcw-my-jsplumb
    newTag: ""

generatorOptions:
  disableNameSuffixHash: false
